ARCHS = armv7 armv7s arm64
include theos/makefiles/common.mk

BUNDLE_NAME = FaceOff7FlipswitchToggle
FaceOff7FlipswitchToggle_FILES = Switch.x
FaceOff7FlipswitchToggle_FRAMEWORKS = UIKit
FaceOff7FlipswitchToggle_LIBRARIES = flipswitch
FaceOff7FlipswitchToggle_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk